import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EventProvider } from "@/utils/provider/EventContext";
import ReactQueryProvider from "@/utils/provider/ReactQueryProvider";
import { CartProvider } from "@/utils/provider/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <ReactQueryProvider> */}
      {/* <EventProvider> */}
      {/* <CartProvider> */}
      <body>{children}</body>
      {/* </CartProvider> */}
      {/* </EventProvider> */}
      {/* </ReactQueryProvider> */}
    </html>
  );
}
